// GazoducActe3Timing.ts — generated by storyboarder agent
// Audio: out/episodes/gazoduc-aagp-tsgp/narration-p3.mp3 | Measured: 123.065760s (ffprobe) | FPS: 30
// Script: memory/episodes/souverain/gazoduc-aagp-tsgp/SCRIPT-V3-VOIX.md (PARTIE 3, lignes 34-41) | Version: LOCKED
// Alignment source: out/episodes/gazoduc-aagp-tsgp/narration-NEW.alignment.json (forced-align ElevenLabs,
// 2105 words, timestamps on the FULL concatenated narration.mp3). Offset of Partie 3 in that file:
// 223.572086s (= P1 84.567075 + P2 139.005011). All timestamps below are RELATIVE to narration-p3.mp3
// (i.e. already offset-corrected) unless explicitly noted "absolute in narration.mp3".
//
// Convention note: this project (GazoducActe1Hook.tsx, GazoducActe2*.tsx) normally embeds timing as
// inline constants per scene file (BEAT_T / S() / AUDIO_SAFETY_MARGIN_F), not a standalone timing.ts.
// This file is produced as an explicit exception per task brief (contract to hand off to the DA-brief
// gate + code phase, before any component is written) — it should be READ and its constants copied/
// imported into the 3 scene files once coded, following the exact same S()/AUDIO_SAFETY_MARGIN_F
// pattern already proven in GazoducActe2AAGP.tsx / GazoducActe2Signature.tsx / GazoducActe2Financement.tsx.
//
// Structure: 3 segments montés bout à bout (même moule que l'Acte 2 — jamais un fichier monolithique,
// cf DOCTRINE-SOUVERAIN.md §4.4):
//   A — Carte D3, tracé TSGP (Nigeria -> Niger -> Algérie)
//   B — Insert SVG scène-lieu, sécurité (zone JNIM/EI + rupture Niamey)
//   C — Insert SVG scène-lieu, paradoxe/clôture (Maroc pacifié vs Algérie autonome)
//
// ⛔ SIGNAL A VERIFIER AVANT CODE (non bloquant, mais a lire) : le dernier mot du fichier P3
// ("conflit.") se termine a 123.148s dans le forced-align, soit 82ms APRES la duree mesuree reelle
// du fichier audio (123.06576s, ffprobe). Le mot est donc leg erement clippe en fin de fichier —
// deja absorbe par AUDIO_SAFETY_MARGIN_F (+9f/300ms) sur le Segment C, comme sur tous les segments
// de l'Acte 2 (meme pattern, meme cause : la Sequence de montage coupe l'Audio net a sa duree sans
// tolerance). Ne pas re-mesurer / re-couper l'audio pour ce delta — le hold visuel absorbe largement.

export const FPS = 30;
const S = (sec: number) => Math.round(sec * FPS);

// ===== Frontières des 3 segments — absolues dans narration-p3.mp3, zéro gap (Règle 3 : silences
// absorbés dans la scène PRÉCÉDENTE) =====
//
// A/B boundary : la phrase pivot "Mais le véritable problème auquel fait face le gazoduc
// transsaharien, c'est le terrain." (mots 73.928s->79.608s) appartient ENTIÈREMENT au Segment B
// (elle amorce le pivot vers la menace sécuritaire) — la frontière tombe donc AVANT "Mais" (73.928s),
// jamais au milieu de cette phrase. Le silence entre "démarrer." (fin 72.348s) et "Mais" (73.928s,
// soit 1.58s) est absorbé dans A.
//
// B/C boundary : la phrase de clôture "C'est le paradoxe de cette course." (103.448s->105.228s)
// appartient à B (elle referme le mouvement Sécurité/attaque, avant que C ouvre sur "Le Maroc...").
// Le silence entre "course." (fin 105.228s) et "Le" (début Maroc, 105.808s, soit 0.58s) est absorbé
// dans B, pas laissé en gap non-attribué (écart corrigé après premier calcul brut — voir alignement
// forced-align, mots index 219/220).

export const SEGMENTS = {
  A_carteTSGP: {
    start: 0,
    end: 2218,
    startSec: 0.0,
    endSec: 73.928,
  },
  B_insertSecurite: {
    start: 2218,
    end: 3174,
    startSec: 73.928,
    endSec: 105.808,
  },
  C_insertParadoxe: {
    start: 3174,
    end: 3692,
    startSec: 105.808,
    endSec: 123.066, // borne sur la durée mesurée réelle (ffprobe), pas sur le mot forced-align clippé
  },
};

// Durée de contenu narratif pur par segment (SANS la marge de sécurité audio — utiliser pour caler
// la fin du GESTE visuel avant le hold). Ajouter AUDIO_SAFETY_MARGIN_F pour la durée totale de la
// Sequence de montage (comportement identique à GazoducActe2AAGP.tsx / Signature.tsx / Financement.tsx).
export const AUDIO_SAFETY_MARGIN_F = 9; // +300ms hold visuel avant coupe nette de l'Audio

export const GAZODUC_A3_CARTE_TSGP_FRAMES = (SEGMENTS.A_carteTSGP.end - SEGMENTS.A_carteTSGP.start) + AUDIO_SAFETY_MARGIN_F; // 2218 + 9 = 2227f (74.233s)
export const GAZODUC_A3_INSERT_SECURITE_FRAMES = (SEGMENTS.B_insertSecurite.end - SEGMENTS.B_insertSecurite.start) + AUDIO_SAFETY_MARGIN_F; // 956 + 9 = 965f (32.167s)
export const GAZODUC_A3_INSERT_PARADOXE_FRAMES = (SEGMENTS.C_insertParadoxe.end - SEGMENTS.C_insertParadoxe.start) + AUDIO_SAFETY_MARGIN_F; // 518 + 9 = 527f (17.567s)

export const TOTAL_FRAMES_CONTENT = SEGMENTS.C_insertParadoxe.end; // 3692f (123.067s) — contenu narratif pur, sans marges
export const TOTAL_SECONDS = 123.06576; // durée mesurée ffprobe, source de vérité

// ============================================================================
// SEGMENT A — Carte D3, tracé TSGP (Nigeria -> Niger -> Algérie)
// Frames ABSOLUES dans narration-p3.mp3 (0 = début du fichier). Le composant de scène doit driver
// son useCurrentFrame() localement (frame locale = frame absolue - SEGMENTS.A_carteTSGP.start = frame
// absolue ici puisque A commence à 0).
// ============================================================================
export const BEATS_A = {
  segStart: 0, // 0.0s — ouverture, Nigeria déjà tracé côté AAGP (Acte 2), point de bifurcation
  traceNigerStart: S(22.248), // 667f — "il traverse le Niger,"
  traceSaharaStart: S(23.888), // 717f — "remonte le Sahara,"
  traceAlgerieApproach: S(27.148), // 814f — "se connecte directement aux réseaux algériens,"
  dateAnnonceStart: S(33.088), // 993f — "Le quatre juin deux mille vingt-six," (annonce officielle)
  adrarArriveEnd: S(42.828), // 1285f — fin de "...dans la région d'Adrar." (climax géographique chantier)
  pelleteusesStart: S(43.068), // 1292f — "Les pelleteuses sont déjà sur le terrain,"
  sonatrachStart: S(45.328), // 1360f — "et Sonatrach, la compagnie nationale,"
  coutEmphaseStart: S(55.028), // 1651f — "DEUX FOIS MOINS CHER" (emphase CAPS script — contraste financement)
  treizeMdsStart: S(59.348), // 1780f — "environ treize milliards de dollars,"
  financementEtatsEnd: S(72.348), // 2170f — fin de "...pour démarrer." (clôture financement souverain)
  segEnd: 2218, // 73.928s — fin du contenu narratif A (avant AUDIO_SAFETY_MARGIN_F)
};

// ============================================================================
// SEGMENT B — Insert SVG scène-lieu, sécurité (zone JNIM/EI + rupture Niamey)
// Frames LOCALES au segment (0 = début de B = 73.928s absolu dans narration-p3.mp3).
// Décor fixe + objets qui s'activent séquentiellement — PAS de figure humaine violente
// (charte analyste, cf feedback_decode-castile-warmap-vivante.md qui a REJETÉ les pions réalistes).
// ============================================================================
export const BEATS_B = {
  segStart: 0, // 73.928s absolu — "Mais le véritable problème..."
  terrainProblemeEnd: S(5.68), // 170f — fin de "...c'est le terrain." (pivot énoncé)
  alQaidaStart: S(10.08), // 302f — "où Al-Qaïda"
  islamiqueEnd: S(11.84), // 355f — fin de "...et l'État islamique"
  actifsEnd: S(13.68), // 410f — fin de "...restent très actifs." (zone de menace établie, hold)
  dateAttaqueStart: S(14.98), // 449f — "Et le vingt-cinq juin deux mille vingt-six,"
  attaqueVerbeStart: S(22.62), // 679f — "une attaque frappe" (bascule dramatique, PAS de visuel violent)
  niameyStart: S(24.56), // 737f — "l'aéroport de Niamey" (lieu de la rupture)
  trenteCinqStart: S(26.46), // 794f — "TRENTE-CINQ" (emphase CAPS script)
  mortsEnd: S(28.08), // 842f — fin de "...MORTS." — climax dramatique du segment, hold requis
  paradoxeStart: S(29.82), // 895f — "C'est le paradoxe" (bascule vers la clôture-résumé)
  courseEnd: S(31.3), // 939f — fin de "...cette course."
  segEnd: 956, // 105.808s absolu — fin du contenu narratif B (avant AUDIO_SAFETY_MARGIN_F)
};

// ============================================================================
// SEGMENT C — Insert SVG scène-lieu, paradoxe/clôture (Maroc pacifié vs Algérie autonome)
// Frames LOCALES au segment (0 = début de C = 105.808s absolu dans narration-p3.mp3).
// Deux "camps"/médaillons qui se répondent visuellement (écho suggéré : cadenas EUR<->CFA du Beat 3 CFA).
// ============================================================================
export const BEATS_C = {
  segStart: 0, // 105.808s absolu — "Le Maroc mise sur..."
  marocStart: S(0.2), // 6f — "Maroc"
  marocPacifieEnd: S(3.34), // 100f — fin de "...tracé pacifié"
  marocPhraseEnd: S(6.78), // 203f — fin de "...accord de financement international." (camp Maroc complet)
  algerieStart: S(7.86), // 236f — "L'Algérie mise sur..." (camp Algérie s'active)
  conflitPhraseEnd: S(17.34), // 520f — fin forced-align de "...zone de conflit." (légèrement > segEnd,
  // cf. signal en tête de fichier — mot clippé 82ms en fin d'audio réel, absorbé par la marge de sécurité)
  segEnd: 518, // 123.066s absolu (=TOTAL_SECONDS) — fin mesurée réelle du fichier audio P3
};

// ============================================================================
// Validation (contrôle indépendant à relancer si régénération audio) :
// - Segment A démarre à frame 0. ✔
// - Segment C se termine à TOTAL_FRAMES_CONTENT (3692) — écart 0.03f vs 123.06576*30=3691.97, rounding only. ✔
// - Zéro gap entre segments : A.end(2218)===B.start(2218), B.end(3174)===C.start(3174). ✔
// - Aucun segment < 30f (1s) : A=2218f, B=956f, C=518f. ✔
// - FPS constant présent. ✔
// ============================================================================
