// timing-abou-bakari.ts — generated by storyboarder agent
// Audio: abou-bakari-narratrice-v1.mp3 | Measured: 82.80s | FPS: 30
// CTA:   beat09-cta-v2.mp3             | Measured: 10.08s
// Total: 82.80 + 10.08 = 92.88s = 2786 frames
// Script: Abou Bakari II | Version: LOCKED 2026-03-14
// Forced-alignment: public/audio/abou-bakari/abou-bakari-alignment.json (316 entries)
// Whisper: src/projects/geoafrique-shorts/whisper-words-abou-bakari.ts (228 words)
//
// Beat boundaries derived from forced-alignment word-level timestamps.
// Silence rule: silences absorbed into PRECEDING beat (not next).
// Beat order = timeline order = narrative order of the audio.
//
// fleet_a: narration continues under clip (audio OFF on clip, not on narration track).
// fleet_b: clip has audio ON.
//
// v2 fixes (2026-04-30):
//   - CTA: beat09-cta-v2.mp3 (10.08s, sans double "Et toi")
//   - fleet_b: etendu visuellement jusqu'a 44.060s (duree naturelle clip 6.06s)
//   - name: demarre a 44.060s (fin fleet_b naturelle)
//   - abdication: demarre a 51.999s (absorbe gap noir 47 frames entre name et abdication)

export const FPS = 30;

export const NARRATION_DURATION_S = 82.80;
export const CTA_DURATION_S = 10.08;
export const TOTAL_SECONDS = NARRATION_DURATION_S + CTA_DURATION_S; // 92.88

// Helper: seconds -> frames
const s = (sec: number) => Math.round(sec * FPS);

// ============================================================
// BEATS — 9 beats in timeline order
//
// Cesure sources (forced-alignment):
//   ocean    end: "savoir."  @ 13.500s | silence 0.299s before "Abou"
//   empire   end: "l'horizon." @ 22.699s | silence 0.360s before "Il"
//   fleet_a  end: "geant."   @ 35.079s | silence 2.921s before "On" (natural dramatic pause)
//   fleet_b  end: "pas."     @ 39.079s | silence 0.060s before "Abou"
//   name     end: "jamais."  @ 51.999s | silence 1.580s before "Son"
//   abdication end: "dollars." @ 66.899s | silence 0.101s before "Abou"
//   obsession  end: "l'ouest." @ 72.859s | silence 0.041s before "Cent"
//   colomb     end: "decouvreur." @ 79.319s | silence 0.100s before "Mais"
//   close_cta  end: 82.800s (narration end) + 12.16s CTA = 94.96s
//
// Clip durations measured with ffprobe:
//   empire-v1.mp4      : 9.06s
//   fleet-a-v1.mp4     : 10.04s  (AUDIO OFF — narration still plays under clip)
//   fleet-b-v1.mp4     : 6.06s
//   name-v1.mp4        : 10.12s
//   abdication-v1.mp4  : 10.04s  (+ caravane extract ~4s from out/abou-bakari-final.mp4)
//   ocean-v1.mp4       : 10.05s  (only 0-6s used for obsession beat)
//   colomb-v1.mp4      : 6.06s
// ============================================================

export const BEATS = {

  // Beat 01 — ocean
  // Globe Remotion V2 animation (not a Seedance clip)
  // Narration: "En 1311, l'ocean Atlantique n'est qu'un mur de brouillard.
  //             Personne n'ose regarder vers l'ouest. Sauf un homme
  //             qui a un ardent desir de savoir."
  // Cesure: fin "savoir." @ 13.500s | mot suivant "Abou" @ 13.799s
  ocean: {
    start:    s(0.000),   // frame 0
    end:      s(13.500),  // frame 405
    startSec: 0.000,
    endSec:   13.500,
    // Narration starts at 0.119s (first word "En") — 0.000 gives buffer at top
    narrationOffsetS: 0.000,
  },

  // Beat 02 — empire
  // Clip: empire-v1.mp4 (9.06s) — muted
  // Narration: "Abou Bakari deux. Mansa du Mali. Roi des rois.
  //             Il regne sur l'empire le plus riche du monde. Hante par l'horizon."
  // Cesure: fin "l'horizon." @ 22.699s | mot suivant "Il" @ 23.059s (silence 0.360s)
  empire: {
    start:    s(13.799),  // frame 414
    end:      s(22.699),  // frame 681
    startSec: 13.799,
    endSec:   22.699,
    narrationOffsetS: 13.799,
  },

  // Beat 03 — fleet_a (AUDIO OFF on clip, narration continues)
  // Clip: fleet-a-v1.mp4 (10.04s) — clip muted (content policy), narration track active
  // Narration: "Il fait preparer deux mille pirogues.
  //             Un seul bateau revient. Le capitaine est terrifie.
  //             Un courant geant."
  // Cesure: fin "geant." @ 35.079s + silence 2.921s absorbed here = end @ 38.000s
  // (Silence rule: silence belongs to the beat that just ended.)
  fleet_a: {
    start:    s(23.059),  // frame 692
    end:      s(38.000),  // frame 1140  (includes 2.921s silence after "geant.")
    startSec: 23.059,
    endSec:   38.000,
    narrationOffsetS: 23.059,
    audioOff: true,       // clip muted; narration track continues underneath
  },

  // Beat 04 — fleet_b (audio ON on clip)
  // Clip: fleet-b-v1.mp4 (6.06s) — audio ON
  // Narration: "On ne passe pas."
  // "On" starts @ 38.000s | fin "pas." @ 39.079s
  // Audio boundary: 39.139s (0.060s silence absorbed)
  // Visual boundary: 44.060s (full natural clip duration 6.06s from 38.000s)
  // Note: beat Sequence in main comp uses Math.round(6.06 * FPS) = 182 frames
  fleet_b: {
    start:    s(38.000),  // frame 1140
    end:      s(44.060),  // frame 1322  (full clip natural duration for visual)
    startSec: 38.000,
    endSec:   44.060,
    narrationOffsetS: 38.000,
    audioBoundaryS:   39.139,  // actual narration end (used for subtitle sceneEndS)
  },

  // Beat 05 — name
  // Clip: name-v1.mp4 (10.12s) — muted
  // Narration: "Abou Bakari ne recule pas. Il abdique. Il quitte son trone,
  //             son or, son pouvoir. Il monte lui-meme a bord.
  //             Il ne reviendra jamais."
  // Cesure: fin "jamais." @ 51.999s | silence 1.580s | "Son" @ 53.579s
  // Note: starts at fleet_b visual end (44.060s) — no black gap
  name: {
    start:    s(44.060),  // frame 1322
    end:      s(51.999),  // frame 1560
    startSec: 44.060,
    endSec:   51.999,
    narrationOffsetS: 44.060,
  },

  // Beat 06 — abdication
  // Clip: abdication-v1.mp4 (10.04s) + caravane extract from out/abou-bakari-final.mp4 ~65-70s (~4s)
  // Total clip duration target: ~14s (matches narration 13.32s)
  // Narration: "Son demi-frere monte sur le trone. Mansa Moussa.
  //             L'homme le plus riche de toute l'histoire humaine. 400 milliards de dollars."
  // Cesure: fin "dollars." @ 66.899s | mot suivant "Abou" @ 67.000s (silence 0.101s)
  // Note: starts at name.end (51.999s) — absorbe le gap de 47 frames qui causait un ecran noir
  abdication: {
    start:    s(51.999),  // frame 1560  (was 1607, -47 frames, gap black eliminated)
    end:      s(66.899),  // frame 2007
    startSec: 51.999,
    endSec:   66.899,
    narrationOffsetS: 53.579,  // narration "Son" starts here (silence 51.999->53.579 is visual)
  },

  // Beat 07 — obsession
  // Clip: ocean-v1.mp4 (0-6s only; clip is 10.05s total)
  // Narration: "Abou Bakari avait tout abandonne pour une seule obsession :
  //             savoir ce qu'il y avait a l'ouest."
  // Cesure: fin "l'ouest." @ 72.859s | mot suivant "Cent" @ 72.900s (silence 0.041s)
  obsession: {
    start:    s(67.000),  // frame 2010
    end:      s(72.859),  // frame 2186
    startSec: 67.000,
    endSec:   72.859,
    narrationOffsetS: 67.000,
  },

  // Beat 08 — colomb
  // Clip: colomb-v1.mp4 (6.06s) — audio ON, palette froide
  // Narration: "Cent quatre-vingt-un ans plus tard, Christophe Colomb
  //             traverse le meme ocean. On l'appelle le decouvreur."
  // Cesure: fin "decouvreur." @ 79.319s | mot suivant "Mais" @ 79.419s (silence 0.100s)
  colomb: {
    start:    s(72.900),  // frame 2187
    end:      s(79.319),  // frame 2380
    startSec: 72.900,
    endSec:   79.319,
    narrationOffsetS: 72.900,
  },

  // Beat 09 — close_cta
  // Remotion pur: split-screen fleet_a (left) + colomb (right) during narration close,
  // then full CTA screen with beat09-cta-v2.mp3
  // Narration close: "Mais qui a traverse en premier ? Et toi... tu savais ca ?"
  //   (79.419s - 82.800s = 3.381s = 101 frames)
  // CTA audio (beat09-cta-v2.mp3 = 10.08s = 302 frames)
  // Total beat: 3.381s + 10.08s = 13.461s = 404 frames
  close_cta: {
    start:    s(79.419),                             // frame 2383
    end:      s(79.419 + 3.381 + CTA_DURATION_S),   // frame 2786
    startSec: 79.419,
    endSec:   79.419 + 3.381 + CTA_DURATION_S,      // 92.880s
    narrationOffsetS: 79.419,
    // Sub-boundary: CTA audio starts at narrationEnd
    narrationEndFrame: s(NARRATION_DURATION_S),      // frame 2484
    narrationEndSec:   NARRATION_DURATION_S,         // 82.800s
  },

} as const;

// ============================================================
// TOTALS
// ============================================================

export const TOTAL_FRAMES = Math.round(TOTAL_SECONDS * FPS);             // 2786
export const NARRATION_FRAMES = Math.round(NARRATION_DURATION_S * FPS);  // 2484
export const CTA_FRAMES = Math.round(CTA_DURATION_S * FPS);              // 302

// ============================================================
// BEAT REPORT v2 (for reference)
// Beat         | start  |  end  | startSec |  endSec | durSec | durF
// ocean        |      0 |   405 |    0.000 |  13.500 | 13.500 |  405
// empire       |    414 |   681 |   13.799 |  22.699 |  8.900 |  267
// fleet_a      |    692 |  1140 |   23.059 |  38.000 | 14.941 |  448
// fleet_b      |   1140 |  1322 |   38.000 |  44.060 |  6.060 |  182  (visual; narration ends 39.139s)
// name         |   1322 |  1560 |   44.060 |  51.999 |  7.939 |  238  (was 1174, gap eliminated)
// abdication   |   1560 |  2007 |   51.999 |  66.899 | 14.900 |  447  (was 1607, gap eliminated)
// obsession    |   2010 |  2186 |   67.000 |  72.859 |  5.859 |  176
// colomb       |   2187 |  2380 |   72.900 |  79.319 |  6.419 |  193
// close_cta    |   2383 |  2786 |   79.419 |  92.880 | 13.461 |  404
//
// Silence absorption (Storyboarder Rule 3 — silence into preceding beat):
//   ocean    end: "savoir." @ 13.500s; "Abou" @ 13.799s (gap 0.299s) -> absorbed into ocean
//   empire   end: "l'horizon." @ 22.699s; "Il" @ 23.059s (gap 0.360s) -> absorbed into empire
//   fleet_a  end: "geant." @ 35.079s; "On" @ 38.000s (gap 2.921s dramatic) -> absorbed into fleet_a
//   fleet_b  audio: "pas." @ 39.079s; narration boundary 39.139s; visual extended to 44.060s (clip end)
//   name     narration: 44.060s->51.999s; silence 1.580s before "Son" absorbed into abdication visual
//   abdication end: "dollars." @ 66.899s; "Abou" @ 67.000s (gap 0.101s) -> absorbed into abdication
//   obsession  end: "l'ouest." @ 72.859s; "Cent" @ 72.900s (gap 0.041s) -> absorbed into obsession
//   colomb     end: "decouvreur." @ 79.319s; "Mais" @ 79.419s (gap 0.100s) -> absorbed into colomb
// ============================================================
