#!/usr/bin/env python3
"""
improve_storyboard.py — Étape 1.5 du pipeline officiel Souverain.

Usage:
    python3 scripts/improve_storyboard.py <episode> <beat_id> [--apply]

Exemples:
    # Suggère les améliorations et affiche le rapport (pas de régénération)
    python3 scripts/improve_storyboard.py zimbabwe-lithium beat4

    # Suggère les améliorations ET régénère le storyboard amélioré
    python3 scripts/improve_storyboard.py zimbabwe-lithium beat4 --apply

Ce que ce script fait :
  1. Lit le storyboard existant (storyboard-v6/<beat_id>-*.png ou storyboard-v2/)
  2. Envoie à Gemini 3.1-pro-preview en multimodal
  3. 3.1-pro analyse et suggère des améliorations dans nos contraintes Remotion
  4. Sauvegarde le rapport JSON + le prompt amélioré
  5. Si --apply : régénère le storyboard via Flash avec le prompt amélioré
  6. Affiche les suggestions pour validation humaine

Ce script NE fait PAS :
  - Le breakdown technique (c'est prepare_beat.py)
  - Coder quoi que ce soit
  - Décider à la place d'Aziz

Quand lancer : APRÈS avoir approuvé le storyboard de base Flash,
               AVANT de lancer prepare_beat.py (breakdown).
"""

import json
import os
import sys
import time
from pathlib import Path

try:
    from google import genai
    from google.genai import types
except ImportError:
    print("Installer: pip install google-genai")
    sys.exit(1)

BASE = Path(__file__).parent.parent


def _load_gemini_key() -> str:
    key = os.environ.get("GEMINI_API_KEY")
    if key:
        return key
    env_file = BASE / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if line.startswith("GEMINI_API_KEY="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    print("ERROR: GEMINI_API_KEY introuvable (env ou .env)")
    sys.exit(1)


GEMINI_API_KEY = _load_gemini_key()

IMPROVE_PROMPT_TEMPLATE = """You are a senior creative director for a French documentary YouTube channel called Souverain.
You are looking at a storyboard frame generated by AI for a beat in an episode.

Your task: suggest VISUAL IMPROVEMENTS to make this storyboard more premium, atmospheric and cinematic — while staying strictly within our technical constraints.

BEAT CONTEXT:
- Episode: {episode}
- Beat: {beat_id}
- Final output: Remotion (React) animated video, portrait 9:16, 1080x1920
- Style: Souverain documentary — dark navy/black base, gold accents (#c8a951), ivory text (#f0e8d8)

STRICT CONSTRAINTS (every suggestion MUST respect ALL of these):
1. No 3D rendering, no particle physics, no After Effects
2. Everything reproducible in React CSS + SVG inline + PNG assets
3. Text must remain CSS (never burned into PNG assets)
4. Maximum 3-4 distinct visual elements (clarity over complexity)
5. Assets on dark backgrounds: generate on pure black #000000, use mix-blend-mode: screen in Remotion
6. Assets on light backgrounds: generate on solid cream #d4c29d
7. SVG shapes (arrows, circles, lines) are coded directly, not generated as PNG

BACKGROUND RULES (critical — do NOT violate):
Only 3 background types are valid for Souverain:
  A. CSS dots grid on dark navy #080d14 — preferred for data-viz and statement beats
  B. Aged paper/kraft texture PNG — for document/dossier beats only
  C. SVG geometric ornament code — for climax beats only
NEVER suggest: smoky, atmospheric, photographic, clouds, fire, fog, smoke, cinematic texture, organic texture.
These look like stock photos and break the Souverain aesthetic.

GEOGRAPHY RULES (critical):
If the storyboard shows a country silhouette or map outline:
- It must come from d3-geo + Natural Earth GeoJSON (NOT a hand-drawn SVG path)
- Never suggest a "placeholder" or "approximate" SVG path for geography
- Instead, specify: "use d3-geo with Natural Earth 50m, ISO code = [XXX]"

RETURN a JSON with this exact structure:
{{
  "current_analysis": "honest 2-3 sentence assessment — what works, what is flat or missing",
  "improvements": [
    {{
      "element": "name of element to change or add",
      "current": "what it looks like now (or 'absent')",
      "suggested": "concrete visual improvement",
      "why": "visual impact reason (1 sentence)",
      "implementation": "how to implement in Remotion (CSS/SVG/PNG asset)",
      "feasible_in_remotion": true
    }}
  ],
  "improved_storyboard_prompt": "Complete prompt for Gemini Flash to regenerate this storyboard with all improvements. English. Optimized for gemini-3.1-flash-image-preview. Must end with: NO TEXT, NO LETTERS, NO NUMBERS in the image.",
  "background_asset_prompt": "Prompt for the background PNG specifically (texture, mood, colors, atmosphere). This will be generated separately as a PNG asset.",
  "animation_hints": "How the key elements should animate when coded (entrance, movement, timing relative to voice-over)"
}}

Return ONLY valid JSON."""

SOUVERAIN_CONSTRAINTS = """

ABSOLUTE RULES FOR THE REGENERATED STORYBOARD:
- NO TEXT, NO LETTERS, NO NUMBERS anywhere in the image
- Portrait format 9:16
- Dark background (navy/black) unless explicitly specified otherwise
- Gold accent #c8a951 for key visual elements
- Cinematic, editorial, premium feel
- Flat graphic style — no 3D render, no photorealism unless it's a texture/background"""


def find_storyboard(episode_dir: Path, beat_id: str) -> Path | None:
    """Cherche le meilleur storyboard disponible (v6 > v5 > v2 > v1)."""
    for version in ["storyboard-v6", "storyboard-v5", "storyboard-v2", "storyboard-v1"]:
        folder = episode_dir / "assets" / version
        if not folder.exists():
            continue
        # Chercher fichier contenant beat_id
        for f in folder.glob(f"{beat_id}*.png"):
            return f
        # Fallback: chercher par numéro
        beat_num = beat_id.replace("beat", "")
        for f in folder.glob(f"beat{beat_num}*.png"):
            return f
    return None


def run(episode: str, beat_id: str, apply: bool):
    client = genai.Client(api_key=GEMINI_API_KEY)
    episode_dir = BASE / "public" / "souverain" / episode

    # Trouver le storyboard
    storyboard_path = find_storyboard(episode_dir, beat_id)
    if not storyboard_path:
        print(f"ERREUR : aucun storyboard trouvé pour {episode}/{beat_id}")
        print("Générer d'abord le storyboard avec Gemini Flash.")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"IMPROVE STORYBOARD — {episode} / {beat_id}")
    print(f"{'='*60}")
    print(f"Storyboard source : {storyboard_path.name}")
    print(f"Mode : {'APPLY (régénération)' if apply else 'ANALYSE seule'}\n")

    img_part = types.Part.from_bytes(
        data=storyboard_path.read_bytes(),
        mime_type="image/png"
    )

    prompt = IMPROVE_PROMPT_TEMPLATE.format(episode=episode, beat_id=beat_id)

    print("Analyse par Gemini 3.1-pro-preview...")
    response = client.models.generate_content(
        model="gemini-3.1-pro-preview",
        contents=[prompt, img_part],
        config=types.GenerateContentConfig(
            temperature=0.6,
            response_mime_type="application/json",
        ),
    )

    data = json.loads(response.text)

    # Sauvegarder le rapport
    out_dir = episode_dir / "assets" / "storyboard-v6"
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / f"{beat_id}-improvements.json"
    report_path.write_text(json.dumps(data, ensure_ascii=False, indent=2))

    # Afficher le rapport
    print(f"\n{'─'*50}")
    print("ANALYSE ACTUELLE")
    print(f"{'─'*50}")
    print(data.get("current_analysis", ""))

    print(f"\n{'─'*50}")
    print("AMÉLIORATIONS SUGGÉRÉES")
    print(f"{'─'*50}")
    for i, imp in enumerate(data.get("improvements", []), 1):
        feasible = "✓" if imp.get("feasible_in_remotion") else "⚠️"
        print(f"\n{feasible} {i}. {imp['element']}")
        print(f"   Actuel    : {imp['current']}")
        print(f"   Suggéré   : {imp['suggested']}")
        print(f"   Pourquoi  : {imp['why']}")
        print(f"   Remotion  : {imp.get('implementation', 'N/A')}")

    print(f"\n{'─'*50}")
    print("ATMOSPHÈRE BACKGROUND")
    print(f"{'─'*50}")
    print(data.get("background_asset_prompt", ""))

    print(f"\n{'─'*50}")
    print("ANIMATION HINTS")
    print(f"{'─'*50}")
    print(data.get("animation_hints", ""))

    print(f"\nRapport sauvegardé : {report_path}")

    if not apply:
        print(f"\n{'='*60}")
        print("Pour régénérer le storyboard avec ces améliorations :")
        print(f"  python3 scripts/improve_storyboard.py {episode} {beat_id} --apply")
        return

    # --apply : régénérer le storyboard
    print(f"\n{'─'*50}")
    print("RÉGÉNÉRATION DU STORYBOARD AMÉLIORÉ...")
    print(f"{'─'*50}")

    improved_prompt = data.get("improved_storyboard_prompt", "") + SOUVERAIN_CONSTRAINTS

    response2 = client.models.generate_content(
        model="gemini-3.1-flash-image-preview",
        contents=[improved_prompt],
        config=types.GenerateContentConfig(
            response_modalities=["image", "text"],
            temperature=0.5,
        ),
    )

    for part in response2.candidates[0].content.parts:
        if part.inline_data and part.inline_data.mime_type.startswith("image/"):
            improved_path = out_dir / f"{beat_id}-improved.png"
            improved_path.write_bytes(part.inline_data.data)
            print(f"✓ Storyboard amélioré : {improved_path}")
            print(f"\nÉtape suivante : valider visuellement le storyboard amélioré,")
            print(f"puis lancer : python3 scripts/prepare_beat.py {episode} {beat_id}")
            break


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 scripts/improve_storyboard.py <episode> <beat_id> [--apply]")
        sys.exit(1)

    apply_flag = "--apply" in sys.argv
    run(sys.argv[1], sys.argv[2], apply=apply_flag)
