// Terminal ticker messages per segment (Script V2)
export const TICKER_MESSAGES: Record<0 | 1 | 2, string> = {
  0: "/// ANALYSE EN COURS... /// 1347 -- DETECTION PATHOGENE INCONNU /// LA MOITIE DE L'EUROPE VA MOURIR /// LES REFLEXES HUMAINS SUIVENT UN ETERNEL SCRIPT /// SCAN COMPORTEMENTAL EN COURS... ///",
  1: "/// SEGMENT : LES FLAGELLANTS /// PROCESSIONS DE 10 000 PERSONNES /// FRERES DE LA CROIX -- 33.5 JOURS DE MARCHE /// FOUETS A POINTES DE FER -- TROIS SEANCES PAR JOUR /// RESULTAT : PROPAGATION ACCELEREE DE LA PESTE ///",
  2: "/// SEGMENT : BOUCS EMISSAIRES /// 1349 -- RUMEUR : EMPOISONNEMENT DES PUITS /// STRASBOURG 14 FEV 1349 -- 2000 BRULES /// MAYENCE -- 6000 EN UN JOUR /// 300+ POGROMS DOCUMENTES /// MOTIVATION REELLE : EFFACEMENT DES DETTES ///",
};
